server:
  port: 8080
database:
  host: localhost
  port: 3306
  user: root
  password: 1234
  dbname: go_video
redis:
  host: localhost
  port: 6379
  password:
  db: 0
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
jwt:
  jwt_secret: 1234
cos:
  bucket: go-video-1370013991
  region: ap-chengdu
  secret_id:
  secret_key:
  public_base_url:
  timeout_seconds: 10
observability:
  pprof:
    enabled: true
    api_addr: localhost:6060
    worker_addr: localhost:6061
